project_id = "tvxydsagumrognunvezk"

[functions.products-api]
verify_jwt = false

[functions.orders-api]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.user-api]
verify_jwt = false

[functions.payments-api]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false