// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvxydsagumrognunvezk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eHlkc2FndW1yb2dudW52ZXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Njg2NDQsImV4cCI6MjA3MzU0NDY0NH0.jZMd6bC-AGD3dGk4XiuASHEuzxiMRU6_oNiXe0bLBMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});